services:
  server:
    build:
      context: ./server/
    image: skelton-server
    container_name: skelton-server
    init: true
    ports:
      - "8080:8080"
  
  webapp:
    build:
      context: ./webapp
    image: skelton-webapp
    container_name: skelton-webapp
    init: true
    ports:
      - "3000:3000"
    volumes:
      - "./webapp:/app"